---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/trackers/{gps_id}/points":
    parameters:
    - name: gps_id
      in: path
      description: gps_id
      required: true
      schema:
        type: string
    post:
      summary: create point
      tags:
      - point
      parameters: []
      responses:
        '201':
          description: point created
        '422':
          description: invalid request
        '404':
          description: tracker not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                record_time:
                  type: string
                  format: date-time
                  required: 'true'
                lat:
                  type: number
                  minumum: -90.0
                  maximum: 90.0
                  format: float
                  required: 'true'
                lng:
                  type: number
                  minimum: -180
                  maximum: 180.0
                  format: float
                  required: 'true'
              required:
              - record_time
              - lat
              - lng
    get:
      summary: list points
      responses:
        '200':
          description: successful
        '404':
          description: tracker not found
  "/api/trackers":
    post:
      summary: create tracker
      tags:
      - tracker
      parameters: []
      responses:
        '201':
          description: tracker created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gps_id:
                  type: string
                driver_initials:
                  type: string
                vehicle_registration_id:
                  type: string
              required:
              - gps_id
              - driver_initials
              - vehicle_registration_id
    get:
      summary: list trackers
      tags:
      - tracker
      responses:
        '200':
          description: successful
  "/api/trackers/{gps_id}":
    get:
      summary: show tracker
      tags:
      - tracker
      parameters:
      - name: gps_id
        in: path
        description: id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: Tracker not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
